name: format and lint

on:
  push:
    branches: [ work ]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: format and lint
        run: |
          npm install
          npm run prettier
          npm run lint
