name: format and lint

on:
  push:
    branches: [ work ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Prettier
        run: npm run format
        
      - name: ESLint
        run: npm run lint